// Package domain implements `orchustr new node|topology` scaffolding rules.
package domain

import (
	"fmt"
	"path/filepath"
	"regexp"

	initdomain "github.com/Regent33/Orchustr/cli/features/initproject/domain"
	"github.com/Regent33/Orchustr/cli/shared/kernel/clierr"
	"github.com/Regent33/Orchustr/cli/shared/kernel/projectcfg"
)

// FileWriter is the data-layer port that persists scaffolded files.
type FileWriter interface {
	Write(path string, contents []byte) error
}

// identPattern keeps generated names valid as identifiers in every language.
var identPattern = regexp.MustCompile(`^[a-z][a-z0-9_]{0,63}$`)

// ScaffoldUseCase adds node and topology stubs to an existing project.
type ScaffoldUseCase struct {
	writer FileWriter
}

// NewScaffoldUseCase wires the use case with its writer dependency.
func NewScaffoldUseCase(writer FileWriter) *ScaffoldUseCase {
	return &ScaffoldUseCase{writer: writer}
}

// Node writes a language-appropriate handler stub under <project>/nodes.
func (uc *ScaffoldUseCase) Node(projectDir, name string) (string, error) {
	if err := validateName(name); err != nil {
		return "", err
	}
	cfg, err := projectcfg.Load(projectDir)
	if err != nil {
		return "", err
	}
	language := initdomain.Language(cfg.Project.Language)
	path := filepath.Join(projectDir, "nodes", name+"."+language.FileExtension())
	if err := uc.writer.Write(path, []byte(nodeTemplate(language, name))); err != nil {
		return "", err
	}
	return path, nil
}

// Topology writes a Rust LoopTopology stub at the project root.
func (uc *ScaffoldUseCase) Topology(projectDir, name string) (string, error) {
	if err := validateName(name); err != nil {
		return "", err
	}
	if _, err := projectcfg.Load(projectDir); err != nil {
		return "", err
	}
	path := filepath.Join(projectDir, name+"_topology.rs")
	if err := uc.writer.Write(path, []byte(topologyTemplate(name))); err != nil {
		return "", err
	}
	return path, nil
}

func validateName(name string) error {
	if !identPattern.MatchString(name) {
		return clierr.New(clierr.KindValidation,
			"name %q must start with a lowercase letter and use only [a-z0-9_] (max 64 chars)", name)
	}
	return nil
}

func nodeTemplate(language initdomain.Language, name string) string {
	switch language {
	case initdomain.LangPython:
		return fmt.Sprintf("async def %s(state):\n    return state\n", name)
	case initdomain.LangTypescript:
		return fmt.Sprintf("export async function %s(state: unknown) {\n  return state;\n}\n", name)
	case initdomain.LangDart:
		return fmt.Sprintf("Future<dynamic> %s(dynamic state) async => state;\n", name)
	default:
		return fmt.Sprintf("pub async fn %s() {}\n", name)
	}
}

func topologyTemplate(name string) string {
	return fmt.Sprintf(`use or_core::DynState;
use or_loom::GraphBuilder;
use or_sentinel::LoopTopology;

/// Custom topology scaffold generated by the orchustr CLI.
pub struct %[1]sTopology;

impl LoopTopology for %[1]sTopology {
    fn build(&self) -> GraphBuilder<DynState> {
        GraphBuilder::new()
    }

    fn name(&self) -> &'static str {
        "%[1]s"
    }
}
`, name)
}
